- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    # - !type:CharacterDepartmentTimeRequirement # WWDP
    #   department: Medical
    #   min: 14400 #4 hrs
    - !type:CharacterEmployerRequirement
      employers:
      - ZengHuPharmaceuticals
      - Interdyne
      - NanoTrasen
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  - Paramedic
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 3 # WWDP

- type: startingGear
  id: DoctorGear
  subGear:
  - DoctorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    id: MedicalPDA
    ears: ClothingHeadsetMedical

- type: startingGear
  id: DoctorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMedicalDoctor
    head: ClothingHeadEnvirohelmMedicalDoctor
    gloves: ClothingHandsGlovesEnviroglovesWhite
