- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    # WD EDIT START
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 28800 # DeltaV - 8 hours
    # WD EDIT END
    - !type:CharacterEmployerRequirement
      employers:
      - Interdyne
      - NanoTrasen
      - ZengHuPharmaceuticals
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External
  - Paramedic
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2 # WD EDIT

- type: startingGear
  id: ParamedicGear
  subGear:
  - ParamedicPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackParamedicFilledDV
    shoes: ClothingShoesColorBlue
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    # WD EDIT START
    # belt: ClothingBeltMedicalEMTFilled
    # pocket1: HandheldGPSBasic
    # pocket2: HandheldCrewMonitor
    # WD EDIT END

- type: startingGear
  id: ParamedicPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitParamedic
    head: ClothingHeadEnvirohelmParamedic
    gloves: ClothingHandsGlovesEnviroglovesNitrile
    shoes: ClothingShoesColorBlue
