- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
  # - !type:CharacterDepartmentTimeRequirement # WWDP
  #   department: Security
  #   min: 36000 # 10 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
    - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - PMCG
      - NanoTrasen
      - EastOrionCompany
    - !type:CharacterOverallTimeRequirement # WWDP
      min: 3600
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: SecurityOfficerGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity # WD EDIT: ClothingBackpackSecurity -> ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - WD EDIT
    # head: ClothingHeadHelmetBasic - WD EDIT
    # outerClothing: ClothingOuterArmorPlateCarrier - WD EDIT
    id: SecurityPDA
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    # belt: ClothingBeltSecurityFilled - WD EDIT
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity

- type: startingGear
  id: SecurityOfficerPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSec
    head: ClothingHeadEnvirohelmSec
    gloves: ClothingHandsGlovesEnviroglovesBlack
