#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  subGear:
  - SyndicatePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate

#Space Ninja Outfit
- type: startingGear
  id: SpaceNinjaGear
  subGear:
  - SpaceNinjaPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    # belt holds katana so satchel has the tools for sabotaging things
    back: ClothingBackpackSatchelNinjaTools
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
    suitstorage: OxygenTankFilled
  inhand:
  - JetpackBlackFilled

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  subGear:
  - ERTPlasmamanGear # TODO: death squad envirosuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquadFilled
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesGlassesMedSec # WWDP
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: OxygenTankFilled # WWDP
    shoes: ClothingShoesBootsMagSecAdv # WWDP
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingDeathsquadFilled # WWDP
  innerClothingSkirt: ClothingUniformJumpsuitDeathSquad # WWDP

#Syndicate Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateOperativeGearFull
  subGear:
  - SyndicateOperativePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  subGear:
  - SyndicateOperativePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    neck: SyndicateWhistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieCommander
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  inhand:
  - NukeOpsDeclarationOfWar
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  subGear:
  - SyndicateOperativePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperativeMedic
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicateAgent
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbingMedFilled
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperativeMedic
  duffelbag: ClothingBackpackDuffelSyndicateOperativeMedic

#Syndicate Lone Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio60TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  subGear:
  - SyndicateOperativePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  subGear:
  - SyndicateOperativePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    gloves: ClothingHandsGlovesCombat
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  subGear:
  - CBURNPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURNFilled
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
  innerClothingSkirt: ClothingUniformJumpsuitColorBrown
  satchel: ClothingBackpackDuffelCBURNFilled
  duffelbag: ClothingBackpackDuffelCBURNFilled

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# Passenger but without the ID, bag, or headset

- type: startingGear
  id: LimitedPassengerGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  innerClothingSkirt: ClothingUniformJumpskirtColorGrey

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  subGear:
  - DeathMatchPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  inhand:
  - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHoldingAdmin
    id: AdminPDA

#Head Rev Gear
- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - RevolutionaryManifesto

#Thief Gear
- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - ToolboxThief
    - ClothingHandsChameleonThief

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  subGear:
  - ClownPlasmamanGear # TODO: Banana clown plasmaman starting gear
  equipment:
    id: ClownPDA
    back: ClothingBackpackClownFilled # WD EDIT: ClothingBackpackClown -> ClothingBackpackClownFilled
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    ears: ClothingHeadsetService
    pocket1: BikeHorn
    pocket2: ClownRecorder

#Clown Troupe
- type: startingGear
  id: ClownTroupe
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    id: ClownPDA
    back: ClothingBackpackClown
    ears: ClothingHeadsetService
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder

#Lost Cargo Tech
- type: startingGear
  id: LostCargoTechGearSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCargosoft
    id: CargoPDA
    back: ClothingBackpackCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool

- type: startingGear
  id: LostCargoTechGearCoat
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesBootsWinterCargo
    head: ClothingHeadHatCargosoft
    id: CargoPDA
    back: ClothingBackpackDuffelCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    outerClothing: ClothingOuterWinterCargo

#Traveling Chef
- type: startingGear
  id: TravelingChef
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    shoes: ClothingShoesColorWhite
    id: ChefPDA
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetService
    belt: ClothingBeltChef

#CMO Disaster Victim
- type: startingGear
  id: DisasterVictimCMO
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    shoes: ClothingShoesColorBrown
    head: ClothingHeadMirror
    neck: ClothingCloakCmo
    id: CMOPDA
    back: ClothingBackpackMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

- type: startingGear
  id: DisasterVictimCMOAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMOTurtle
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretCmo
    neck: ClothingNeckMantleCMO
    id: CMOPDA
    back: ClothingBackpackSatchelMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

#Captain Disaster Victim
- type: startingGear
  id: DisasterVictimCaptain
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCaptain
    neck: ClothingNeckCloakCap
    id: CaptainPDA
    back: ClothingBackpackCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

- type: startingGear
  id: DisasterVictimCaptainAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCapcap
    neck: ClothingNeckMantleCap
    id: CaptainPDA
    back: ClothingBackpackSatchelCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

#RD Disaster Victim
- type: startingGear
  id: DisasterVictimRD
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckCloakRd
    id: RnDPDA
    back: ClothingBackpackScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD

- type: startingGear
  id: DisasterVictimRDAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckMantleRD
    id: RnDPDA
    back: ClothingBackpackSatchelScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD
