- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    # WD EDIT START
    # - !type:CharacterDepartmentTimeRequirement
    #   department: Logistics
    #   min: 21600
    # WD EDIT END
    - !type:CharacterEmployerRequirement
      employers:
      - OrionExpress
      - PMCG
      - NanoTrasen
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  subGear:
  - SalvageSpecialistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvageFilled # WD EDIT: ClothingShoesBootsSalvage -> ClothingShoesBootsSalvageFilled
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    pocket1: MiningVoucher

- type: startingGear
  id: SalvageSpecialistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSalvage
    head: ClothingHeadEnvirohelmSalvage
    gloves: ClothingHandsGlovesEnviroglovesSalvage
    mask: ClothingMaskGasExplorer
    pocket1: MiningVoucher
