- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj
  access:
  - Justice
  - Lawyer
  - Maintenance
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - IdrisIncorporated
    - NanoTrasen

- type: startingGear
  id: LawyerGear
  subGear:
  - LawyerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: BookSecurity
    pocket2: BookSpaceLaw
  inhand:
  - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled
  duffelbag: ClothingBackpackDuffelLawyerFilled

- type: startingGear
  id: LawyerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmColorWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
