- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  guides: [ Traitors ]

- type: antag
  id: TraitorSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-sleeper-objective

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeClothing
  subGear:
  - SyndicatePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    ears: ClothingHeadsetAltSyndicate # WWDP
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsSyndieFilled
    gloves: ClothingHandsGlovesColorBlack

- type: startingGear
  id: SyndicatePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitOperative
    head: ClothingHeadEnvirohelmOperative
    pocket1: DoubleEmergencyPlasmaTankFilled

- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  parent: SyndicateOperativeClothing
  storage:
    back:
    - BoxSurvivalSyndicate
    - WeaponPistolViper
    - MagazinePistol # WWDP
    - MagazinePistol # WWDP
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

- type: startingGear
  id: SyndicateReinforcementMedic
  parent: SyndicateOperativeClothing
  equipment:
    pocket1: WeaponPistolViper
  inhand:
  - MedkitCombatFilled
  storage:
    back:
    - BoxSurvivalSyndicate

- type: startingGear
  id: SyndicateReinforcementSpy
  parent: SyndicateOperativeClothing
  equipment:
    id: AgentIDCard
    mask: ClothingMaskGasVoiceChameleon
    pocket1: WeaponPistolViper
  storage:
    back:
    - BoxSurvivalSyndicate

- type: startingGear
  id: SyndicateReinforcementThief
  parent: SyndicateOperativeClothing
  equipment:
    pocket1: WeaponPistolViper
  inhand:
  - ToolboxSyndicateFilled
  storage:
    back:
    - BoxSurvivalSyndicate
    - SyndicateJawsOfLife

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  parent: SyndicateOperativeGearExtremelyBasic
  equipment:
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    pocket1: BaseUplinkRadio40TC
    id: SyndiPDA
